### PR TITLE
fix: update `default` shell, add missing derivations

### PR DESCRIPTION
**Pull request by drupol**

### CODE REVIEW

**Comment by superherointj** [comment]
As I don't know if you plan any further changes.
Let me know when it is good to merge.

**Comment by drupol** [comment]
It's good now, sorry for that.

**Review by superherointj — APPROVED** [review]

**Comment by superherointj** [comment]
Thanks! Keep coming!

**Comment by drupol** [comment]
I think it's fine now :)

**Comment by superherointj** [comment]
> I think it's fine now :)

The joke is Auto-GPT churn. :D

**Comment by drupol** [comment]
What do you mean?

**Comment by superherointj** [comment]
> What do you mean?

Auto-GPT goes through breaking changes unusually often. I have fixed this repo many times already.
You have just fixed it now. Likely a while later it will break again. It is a moving target.
Upstream is about to release a new version that replaces this one. So, more breaking changes.
As the software is under heavy changes doesn't make sense to settle in any past release version, also because functionality is lacking. This also explains why I haven't packaged it, as a package. It needs to stabilize a bit.

**Comment by drupol** [comment]
Ok fair enough :)

**Comment by drupol** [comment]
I opened a PR: https://github.com/NixOS/nixpkgs/pull/230370

**Pull request merged**
